# Generated by Django 3.2.3 on 2021-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
