# Generated by Django 3.2.3 on 2021-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210516_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('NO', 'Normal'), ('HI', 'High'), ('VH', 'Very High'), ('CR', 'Critical')], max_length=2),
        ),
    ]
