# Generated by Django 3.2.3 on 2021-05-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20210516_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hours_used',
            field=models.FloatField(default=0),
        ),
    ]
