# Generated by Django 3.2.3 on 2021-05-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_client_hours_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contracted_monthly_sem_hours',
            new_name='contracted_monthly_SEM_hours',
        ),
    ]
