# Generated by Django 3.2.3 on 2021-05-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_rename_contracted_monthly_sem_hours_client_contracted_monthly_sem_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='hours_used',
            new_name='hours_used_this_month',
        ),
        migrations.AddField(
            model_name='client',
            name='discontented_client',
            field=models.BooleanField(default=False),
        ),
    ]
