# Generated by Django 3.2.3 on 2021-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20210516_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='priority_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('ST', 'Standard'), ('HI', 'High'), ('VH', 'Very High'), ('CR', 'Critical')], max_length=2),
        ),
    ]
