# Generated by Django 3.2.3 on 2021-05-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_rename_feedback_required_ticket_customer_feedback_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_information', models.TextField()),
                ('date_sent', models.DateTimeField(verbose_name='Date Sent')),
                ('client_responded', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
