# Generated by Django 3.2.3 on 2021-05-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_rename_feedback_request_feedbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
